version: 2.1
orbs:
  katalon-studio: katalon/katalon-studio@23.0.2
workflows:
  build:
    jobs:
      - katalon-studio/run:
          version: latest
          command_arguments: >-
         -retry=0 -testSuitePath="Test Suites/NewTestSuite" -executionProfile="default" -browserType="Chrome" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true